// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    // Single page ./intro.md - Table of Contents
    'intro',
    {
      type: 'category',
      label: 'Civilian',
      items: [
        { type: 'autogenerated', dirName: 'introduction' },
      ],
      collapsible: false,
    },
    {
      type: 'category',
      label: 'CAD',
      items: [
        { type: 'autogenerated', dirName: 'cad' },
      ],
      collapsible: false,
    },
    {
      type: 'category',
      label: 'Law Enforcement',
      items: [
        { type: 'autogenerated', dirName: 'leo' },
      ],
      collapsible: false,
    },
    {
      type: 'category',
      label: 'Fire/EMS',
      items: [
        { type: 'autogenerated', dirName: 'fire-ems' },
      ],
      collapsible: false,
    },
  ],
};

export default sidebars;
