// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    'intro',
    {
      type: "link",
      label: "What's New? 👀",
      href: "/blog/",
    },
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        { type: 'autogenerated', dirName: '1-getting-started' },
      ],
      collapsible: true,
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Your Characters',
      items: [
        { type: 'autogenerated', dirName: '2-your-characters' },
      ],
      collapsible: true,
    },
    {
      type: 'category',
      label: 'Your Vehicles',
      items: [
        { type: 'autogenerated', dirName: '3-your-vehicles' },
      ],
      collapsible: true,
    },
    {
      type: 'category',
      label: 'Postals and Blips',
      items: [
        { type: 'autogenerated', dirName: '4-postal-codes' },
      ],
      collapsible: true,
    },
    {
      type: 'category',
      label: 'Things To Do',
      items: [
        { type: 'autogenerated', dirName: '5-things-to-do' },
      ],
      collapsible: true,
    },
    {
      type: 'category',
      label: 'KC Menu',
      items: [
        { type: 'autogenerated', dirName: '6-kc-menu' },
      ],
      collapsible: true,
    },
    {
      type: 'category',
      label: 'Our CAD',
      items: [
        { type: 'autogenerated', dirName: '7-the-cad' },
      ],
      collapsible: true,
    },
    {
      type: 'category',
      label: 'Law Enforcement',
      items: [
        { type: 'autogenerated', dirName: '8-law-enforcement' },
      ],
      collapsible: true,
    },
    {
      type: 'category',
      label: 'Fire and EMS',
      items: [
        { type: 'autogenerated', dirName: '9-fire-ems' },
      ],
      collapsible: true,
    },
    {
      type: 'category',
      label: 'Our Anti-Cheat',
      items: [
        { type: 'autogenerated', dirName: '10-anticheat' },
      ],
      collapsible: true,
    }
  ],
};

export default sidebars;
