name: Notify Discord

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Send Notification
        env:
          DISCORD_WEBHOOK_URL: "https://discord.com/api/webhooks/1362607277441552517/2WT7hZBlyQ6boJejURiRxAYMr12PEp3S5I2KtvBmO_IKL5oktZ-pXE5xAo5twEktVRAS"
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
          COMMIT_AUTHOR: ${{ github.event.head_commit.author.name }}
          TARGET_BRANCH: ${{ github.event.base_ref }}
        run: |
          discord_title="Commit to branch '${TARGET_BRANCH}' by ${COMMIT_AUTHOR}"

          discord_description=$(cat <<EOF
          ${COMMIT_MESSAGE}
          EOF
          )

          payload=$(jq -n \
            --arg title "$discord_title" \
            --arg description "$discord_description" \
            --argjson color 16711680 \
            '{
              "embeds": [
                {
                  "title": $title,
                  "description": $description,
                  "color": $color
                }
              ]
            }')

          echo "Sending notification for PR targeting branch: $TARGET_BRANCH"
          echo "Payload: $payload"

          curl -X POST -H "Content-Type: application/json" \
            -d "$payload" \
            "$DISCORD_WEBHOOK_URL"
