name: Notify Discord

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Send Notification
        env:
          DISCORD_WEBHOOK_URL: "https://discord.com/api/webhooks/1362607277441552517/2WT7hZBlyQ6boJejURiRxAYMr12PEp3S5I2KtvBmO_IKL5oktZ-pXE5xAo5twEktVRAS" # <-- Insecure: Hardcoded URL

          # --- Commit details ---
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
          COMMIT_AUTHOR_NAME: ${{ github.event.head_commit.author.name }}
          COMMIT_TIMESTAMP: ${{ github.event.head_commit.timestamp }}
          COMMIT_URL: ${{ github.event.head_commit.url }}

          # --- Branch details ---
          TARGET_BRANCH: ${{ github.ref_name }}

          # --- Pusher details (User who ran 'git push') ---
          PUSHER_USERNAME: ${{ github.actor }}
          PUSHER_AVATAR_URL: "https://github.com/${{ github.actor }}.png"

        run: |
          discord_title="Push to '${TARGET_BRANCH}' by ${PUSHER_USERNAME}"

          COMMIT_SHA_SHORT=$(echo "${{ github.sha }}" | cut -c1-7)
          discord_description=$(cat <<EOF
          **Message:**
          ${COMMIT_MESSAGE}
          EOF
          )

          payload=$(jq -n \
            --arg username "$PUSHER_USERNAME" \
            --arg avatar_url "$PUSHER_AVATAR_URL" \
            --arg title "$discord_title" \
            --arg description "$discord_description" \
            --arg timestamp "$COMMIT_TIMESTAMP" \
            --arg commit_url "$COMMIT_URL" \
            --argjson color 3066993 \
            '{
              "username": $username,
              "avatar_url": $avatar_url,
              "embeds": [
                {
                  "title": $title,
                  "description": $description,
                  "url": $commit_url, # Link embed title to commit
                  "timestamp": $timestamp,
                  "color": $color
                }
              ]
            }')

          echo "Sending notification for push to branch: $TARGET_BRANCH by $PUSHER_USERNAME"
          curl -X POST -H "Content-Type: application/json" \
            -d "$payload" \
            "$DISCORD_WEBHOOK_URL"
